# Generated by Django 3.0.2 on 2020-01-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVolunteerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=256)),
                ('hours', models.FloatField()),
                ('date', models.DateTimeField()),
                ('supervisor', models.EmailField(max_length=254)),
                ('number_volunteers', models.IntegerField()),
                ('group_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=256)),
                ('hours', models.FloatField()),
                ('date', models.DateField()),
                ('supervisor', models.CharField(max_length=256)),
            ],
        ),
    ]
