# Generated by Django 2.2.7 on 2019-11-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
