# Generated by Django 2.2.7 on 2019-11-24 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='area_of_interest',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='street_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='work_preference',
            field=models.CharField(choices=[('work_alone', 'Work Alone'), ('work_in_groups', 'Work in Groups')], default='work_alone', max_length=1),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='zipcode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
