# Generated by Django 2.2.7 on 2019-11-30 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0002_auto_20191124_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVolunteerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=256)),
                ('hours', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('supervisor', models.EmailField(max_length=254)),
                ('number_volunteers', models.IntegerField()),
                ('group_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=256)),
                ('hours', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
