# Generated by Django 2.2.6 on 2019-12-01 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0003_groupvolunteerform_volunteerform'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=256)),
                ('hours', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('supervisor', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='GroupVolunteerForm',
            new_name='GroupVolunteerModel',
        ),
        migrations.DeleteModel(
            name='VolunteerForm',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='work_preference',
            field=models.CharField(choices=[('work_alone', 'Work Alone'), ('work_in_groups', 'Work in Groups')], default='work_alone', max_length=14),
        ),
    ]
