# Generated by Django 2.2.6 on 2020-03-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0004_auto_20200309_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='waiver_to_sign',
            field=models.TextField(blank=True),
        ),
    ]
