# Generated by Django 2.2.6 on 2020-03-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0005_auto_20200309_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_contact',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone_number',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_relationship',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
