# Generated by Django 2.2.6 on 2020-01-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0005_auto_20200116_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
