# Generated by Django 2.2.6 on 2020-03-09 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0006_auto_20200309_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='waiver_to_sign',
        ),
        migrations.AddField(
            model_name='profile',
            name='esignature_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='volunteer_waiver_and_release',
            field=models.TextField(blank=True, help_text='San Luis Obispo Botanical Garden (SLOBG) is not responsible for \n\t\tan injury or accident that may occur during my participation as a volunteer in \n\t\tany activity or event. I understand that by signing below I assume full responsibility\n\t\tfor any injury or accident that may occur during my participation as a volunteer, and \n\t\tI hereby release and hold harmless and covenant not to file suit against SLOBG, \n\t\temployees and any affiliated individuals (“releasees”) associated with my \n\t\tparticipation from any loss, liability or claims I may have arising out of my \n\t\tparticipation, including personal injury or damage suffered by me or others, whether \n\t\tcaused by falls, contact with participants, conditions of the facility, negligence of \n\t\tthe releasees or otherwise. If I do not agree to these terms, I understand that I am \n\t\tnot allowed to participate in the volunteer program.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areas_of_interest',
            field=models.TextField(blank=True, help_text='Choose from the following: Education (hours vary), Events (hours vary),\n\t\tGarden Crew (Tuesday 9:00am – 11am), Garden Crew (Thursday 10:00am – 12pm),\n\t\tLibrary, Tuesday (9:00am - 12pm), Maintenance (Hours vary), Marketing/Publicity (Hours vary)\n\t\tMembership (Hours vary), Office Assistant (Hours vary), Plant Records (Tuesday 9:00am - 11am)\n\t\tPropagation Crew (Tuesday 9:00am – 11am), Volunteer Program (Hours vary)', max_length=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Please enter any medical conditions you may have. Write N/A if none.', max_length=512),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Please enter your phone number in the following format: (XXX) XXX-XXXX', max_length=20),
        ),
    ]
