# Generated by Django 2.2.6 on 2020-03-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0007_auto_20200309_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='volunteer_waiver_and_release',
            field=models.CharField(blank=True, help_text='San Luis Obispo Botanical Garden (SLOBG) is not responsible for \n\t\tan injury or accident that may occur during my participation as a volunteer in \n\t\tany activity or event. I understand that by signing below I assume full responsibility\n\t\tfor any injury or accident that may occur during my participation as a volunteer, and \n\t\tI hereby release and hold harmless and covenant not to file suit against SLOBG, \n\t\temployees and any affiliated individuals (“releasees”) associated with my \n\t\tparticipation from any loss, liability or claims I may have arising out of my \n\t\tparticipation, including personal injury or damage suffered by me or others, whether \n\t\tcaused by falls, contact with participants, conditions of the facility, negligence of \n\t\tthe releasees or otherwise. If I do not agree to these terms, I understand that I am \n\t\tnot allowed to participate in the volunteer program.', max_length=50),
        ),
    ]
