# Generated by Django 2.2.6 on 2020-05-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0009_auto_20200309_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='areas_of_interest',
            field=models.CharField(blank=True, help_text='Choose from the following: Education (hours vary), Events (hours vary),\n\t\tGarden Crew (Tuesday 9:00am – 11am), Garden Crew (Thursday 10:00am – 12pm),\n\t\tLibrary, Tuesday (9:00am - 12pm), Maintenance (Hours vary), Marketing/Publicity (Hours vary)\n\t\tMembership (Hours vary), Office Assistant (Hours vary), Plant Records (Tuesday 9:00am - 11am)\n\t\tPropagation Crew (Tuesday 9:00am – 11am), Volunteer Program (Hours vary)', max_length=512),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='activity',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Administration', 'Administration'), ('Outreach', 'Outreach'), ('Education', 'Education')], max_length=256),
        ),
    ]
