# Generated by Django 2.2.6 on 2020-05-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0010_auto_20200501_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='areas_of_interest',
        ),
        migrations.AddField(
            model_name='profile',
            name='areas_of_interest',
            field=models.ManyToManyField(to='slobg_app.ActivityChoice'),
        ),
    ]
