# Generated by Django 3.0.3 on 2020-05-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0010_auto_20200414_0121'),
        ('slobg_app', '0011_auto_20200501_0257'),
    ]

    operations = [
    ]
