# Generated by Django 2.2.6 on 2020-05-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0013_auto_20200505_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrecord',
            name='desc',
        ),
        migrations.AddField(
            model_name='volunteerrecord',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
