# Generated by Django 2.2.6 on 2020-05-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0014_auto_20200505_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_permission',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
