# Generated by Django 2.2.6 on 2020-05-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0015_profile_photo_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_phone_number',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
