# Generated by Django 2.2.6 on 2020-05-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0017_auto_20200524_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_check',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='distribution_list',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_aid_cpr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follow_up_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='harassment_training',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='was_interviewed',
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_phone_number',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
